# Generated by Django 5.0.14 on 2026-04-20 05:02

import apps.notes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to=apps.notes.models.notes_upload_path)),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('uploader_name', models.CharField(max_length=255)),
                ('reader_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_readers',
                'unique_together': {('note', 'user')},
            },
        ),
    ]
