# Generated by Django 5.0.14 on 2026-04-20 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('moderator', 'Moderator')], default='student', max_length=20)),
                ('branch', models.CharField(default='CSE', max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('roadmap_cap', models.IntegerField(default=3)),
                ('last_sprint_start', models.DateTimeField(blank=True, null=True)),
                ('ieee_card_url', models.URLField(blank=True, default='', max_length=500)),
                ('ieee_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='none', max_length=20)),
                ('github_username', models.CharField(blank=True, default='', max_length=255)),
                ('github_connected', models.BooleanField(default=False)),
                ('github_access_token', models.CharField(blank=True, default='', max_length=500)),
                ('github_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('quiz_correct', 'Quiz Correct'), ('daily_login', 'Daily Login'), ('streak_bonus', 'Streak Bonus'), ('note_upload', 'Note Upload'), ('note_read_milestone', 'Note Read Milestone'), ('roadmap_node_complete', 'Roadmap Node Complete'), ('sprint_complete', 'Sprint Complete'), ('weekly_exam', 'Weekly Exam'), ('qotd_correct', 'QOTD Correct')], max_length=100)),
                ('points', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'point_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge', models.CharField(max_length=100)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badges',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
