# Generated by Django 5.0.14 on 2026-04-20 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('posted_by', models.CharField(default='SystemScraper', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placements',
                'ordering': ['-created_at'],
            },
        ),
    ]
