# Generated by Django 5.0.14 on 2026-04-20 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('numerical', 'Numerical'), ('verbal', 'Verbal')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('is_qotd', models.BooleanField(default=False)),
                ('qotd_date', models.DateField(blank=True, null=True)),
                ('is_high_iq', models.BooleanField(default=False)),
                ('target_branch', models.CharField(default='General', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'approved'], name='questions_categor_d405c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='aptitude.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_attempts',
                'unique_together': {('question', 'user')},
            },
        ),
        migrations.CreateModel(
            name='QuestionCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='aptitude.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_corrects',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
